### ISSUE TITLE
Subscription Plan and text not showing properly

### ISSUE THREAD

**Issue by Samson11** [odejinmi/FlutterPaystackPaymentPlus#1]
Whenever i add a plan property to the charge object.
It takes my original amount not the plan's amount.

And in dark mode, the checkout window doesn't display the text when i type in my credentials.

**Comment by odejinmi** [comment]
> Whenever i add a plan property to the charge object. It takes my original amount not the plan's amount.
> 
> And in dark mode, the checkout window doesn't display the text when i type in my credentials.

the sdk works only with the amount, the amount you want to charge your customer should be pass into amount, and for the dark mode we are going to release another version that will take care of that

**Comment by odejinmi** [comment]
> Whenever i add a plan property to the charge object. It takes my original amount not the plan's amount.
> 
> And in dark mode, the checkout window doesn't display the text when i type in my credentials.

can you please share the screenshot where it not showing when you enter your credential

if it is inside your own project try this
bool get isDarkMode {
  var brightness = SchedulerBinding.instance.window.platformBrightness;
  return brightness == Brightness.dark;
} 


color: isDarkMode ? Colors.grey : Colors.black87,
